name: "Cron: Check for updates"

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-wrangler:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.UPDATE_APP_ID }}
          private-key: ${{ secrets.UPDATE_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4

      - name: Install Nix
        uses: "cachix/install-nix-action@v30"

      - name: Update wrangler
        id: update
        run: |
          echo "previous_version=$(nix eval --raw .#wrangler.version)"
          nix run github:Mic92/nix-update -- default --flake --version-regex 'wrangler@(.*)'
          echo "new_version=$(nix eval --raw .#wrangler.version)"

      - name: Create Pull Request
        if: steps.update.outputs.previous_version != steps.update.outputs.new_version
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'wrangler: ${{ steps.update.outputs.previous_version }} -> ${{ steps.update.outputs.new_version }}'
          title: 'wrangler: ${{ steps.update.outputs.previous_version }} -> ${{ steps.update.outputs.new_version }}'
          body: |
            This PR updates the wrangler package to its latest version.
            
            This update was performed automatically by the daily dependency update workflow.
          branch: update-wrangler
          delete-branch: true
          token: ${{ steps.generate-token.outputs.token }}
