name: Build workerd

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: x86_64-linux
            os: ubuntu-latest
          - name: aarch64-linux
            os: ubuntu-24.04-arm
          - name: aarch64-darwin
            os: macos-latest
          - name: x86_64-darwin
            os: macos-13

    name: 'Build'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v31
      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 5G
      - name: Build
        run: nix build .#packages.${{ matrix.name }}.workerd
