name: "Eval"

on:
  push:
    branches:
      - v3
      - v4
  pull_request:
    branches:
      - v3
      - v4

jobs:
  nixExprs:
    name: Nix Exprs
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "cachix/install-nix-action@v31"
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: wrangler
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: ${{ github.event_name == 'pull_request' }}
      - name: Check
        run: nix flake check -L --no-build
  format:
    name: Format
    needs: nixExprs
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "cachix/install-nix-action@v31"
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Check formatting
        run: nix fmt -- -c .
  devShelldefault:
    name: 'devShells / Build default'
    needs: nixExprs
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "cachix/install-nix-action@v31"
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Build
        run: nix build .#devShells.x86_64-linux.default
  packagesWrangler:
    name: 'Packages / Build and check wrangler'
    needs: nixExprs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: wrangler
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: ${{ github.event_name == 'pull_request' }}
      - name: Build
        run: nix build .#packages.x86_64-linux.wrangler
      - name: Version check
        run: ./result/bin/wrangler -v
