name: "Eval (Checks)"

on:
  push:
    branches: 'master'
  pull_request:
    branches: 'master'

jobs:
  wrangler:
    name: wrangler
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "cachix/install-nix-action@v30"
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: wrangler
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: ${{ github.event_name == 'pull_request' }}
      - name: Build
        run: nix build .#checks.x86_64-linux.wrangler
