name: "Eval (Packages)"

on:
  push:
  pull_request_target:

jobs:
  wrangler:
    name: Build wrangler
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "cachix/install-nix-action@V28"
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Build
        run: nix build .#packages.x86_64-linux.wrangler