name: "Eval"

on:
  push:
    branches: 'master'
  pull_request:
    branches: 'master'

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "cachix/install-nix-action@v30"
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Check formatting
        run: nix fmt -- -c .
