name: "Eval (devShells)"

on:
  push:
    branches: 'master'
  pull_request:
    branches: 'master'

jobs:
  wrangler:
    name: Build default
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "cachix/install-nix-action@V28"
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Build
        run: nix build .#devShells.x86_64-linux.default
