name: "Eval (Packages)"

on:
  push:
    branches:
      - v3
      - v4
  pull_request:
    branches:
      - v3
      - v4

jobs:
  wrangler:
    name: Build wrangler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: wrangler
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: ${{ github.event_name == 'pull_request' }}
      - name: Build
        run: nix build .#packages.x86_64-linux.wrangler
