name: "Eval"

on:
  push:
    branches: 'master'
  pull_request_target:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "cachix/install-nix-action@V28"
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: wrangler
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Check
        run: nix flake check -L