name: "Eval (Packages)"

on:
  push:
    branches: 'master'
  pull_request:
    branches: 'master'

jobs:
  wrangler:
    name: Build wrangler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V28
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: wrangler
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build
        run: nix build .#packages.x86_64-linux.wrangler
