name: "Eval"

on:
  push:
    branches:
      - v3
      - v4
  pull_request:
    branches:
      - v3
      - v4

jobs:
  nixExprs:
    name: Nix Exprs
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "cachix/install-nix-action@v31"
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Check
        run: nix flake check -L --no-build
  format:
    name: Format
    needs: nixExprs
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "cachix/install-nix-action@v31"
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Check formatting
        run: nix fmt -- -c .
  devShelldefault:
    name: 'devShells / Build default'
    needs: nixExprs
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "cachix/install-nix-action@v31"
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Build
        run: nix build .#devShells.x86_64-linux.default
  packagesWrangler:
    strategy:
      matrix:
        include:
          - name: x86_64-linux
            os: ubuntu-latest
          - name: aarch64-linux
            os: ubuntu-24.04-arm
          - name: aarch64-darwin
            os: macos-latest
          - name: x86_64-darwin
            os: macos-13

    name: 'Packages / Build and check wrangler'
    needs: nixExprs
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Nothing but Nix
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm' }}
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'holster'
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: wrangler
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: ${{ github.event_name == 'pull_request' }}
      - name: Build
        run: nix build .#packages.${{ matrix.name }}.wrangler
      - name: Version check
        run: ./result/bin/wrangler -v
