name: PR

on:
  pull_request:
    branches:
      - master
  merge_group:

jobs:
  eval:
    name: Eval
    uses: ./.github/workflows/eval.yml
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  no-pr-failures:
    name: 'No PR Failures'
    needs:
      - eval
    if: ${{ failure() }}
    runs-on: ubuntu-24.04-arm
    steps:
      - run: exit 1
